name: Local Deploy

on:
  workflow_call:
    secrets:
      DOPPLER_TOKEN: 
        required: true

# on:
#   workflow_dispatch:

jobs:
  build_web:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    
    - uses: dopplerhq/secrets-fetch-action@v1.2.0
      id: doppler
      with:
        doppler-token: ${{ secrets.DOPPLER_TOKEN }}
        doppler-project: infra
        doppler-config: dev_telepatia-codescript
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.24.0
    
    - name: Define Flavor file
      run: |
        cat <<EOF > flavor.json
        {
            "ENV": ${{ steps.doppler.outputs.ENV }},
            "CUSTOM_LOCAL": ${{ steps.doppler.outputs.CUSTOM_LOCAL }},
            "DOMAIN": ${{ steps.doppler.outputs.DOMAIN }}
            "APP_TYPE": ${{ steps.doppler.outputs.APP_TYPE }}
        }
        EOF
    
    - name: Build web
      run: |
        echo "DEPLOYMENT_ID=web-$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
        flutter build web \
            --dart-define-from-file=flavor.json \
            --web-renderer canvaskit \
            --source-maps \
            --dart-define=DEPLOYMENT_ID=$DEPLOYMENT_ID \
            --dart-define=GIT_COMMIT_HASH=${{ github.sha }}

    - name: Build document
      run: |
        echo "FLAVOR: local" > build/web/flavor.txt
        echo "DEPLOYMENT_ID: $DEPLOYMENT_ID" >> build/web/flavor.txt
        echo "GIT_COMMIT_HASH: ${{ github.sha }}" >> build/web/flavor.txt
        echo "DEPLOYED_BY: ${{ github.actor }}" >> build/web/flavor.txt
        echo "TIMESTAMP (UTC): $(date -u)" >> build/web/flavor.txt
        echo "TIMESTAMP (Local): $(date)" >> build/web/flavor.txt
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@master
      with:
        name: build
        path: build/web
    
  