name: "Deploy Stage"
on:
    workflow_call:
        secrets:
            CUSTOM_LOCAL:
                required: true
            DOMAIN:
                required: true
            ENV:
                required: true

jobs:
    deploy:
        runs-on: macos-latest
        steps:
            - name: "Check environment variables"
              run: |
                  if [ -z "${{ secrets.CUSTOM_LOCAL }}" ]; then
                      echo "Error: CUSTOM_LOCAL is not set or is empty."
                      exit 1
                  fi
                  if [ -z "${{ secrets.DOMAIN }}" ]; then
                      echo "Error: DOMAIN is not set or is empty."
                      exit 1
                  fi
                  if [ -z "${{ secrets.ENV }}" ]; then
                      echo "Error: ENV is not set or is empty."
                      exit 1
                  fi
                  echo "All required secrets are set."
