name: Dynamic Secret Access

on:
  workflow_dispatch:
    inputs:
      user:
        description: "Nombre del usuario para buscar el secreto"
        required: true

jobs:
  access-secret:
    runs-on: ubuntu-latest
    environment: local
    outputs:
      user_secret: ${{ steps.set-secret.outputs.user_secret }}
    steps:
      - name: Set secret name based on input
        id: set-secret-name
        run: echo "SECRET_NAME=${{ github.event.inputs.user }}" >> $GITHUB_ENV

      - name: Access the secret
        id: set-secret
        shell: bash
        env:
          USER_SECRET: ${{ secrets[env.SECRET_NAME] || 'SECRET_NOT_FOUND' }}
        run: |
          if [ "$USER_SECRET" = "SECRET_NOT_FOUND" ]; then
            echo "El secreto para el usuario no existe o no fue encontrado."
            exit 1
          else
            echo "::set-output name=user_secret::$USER_SECRET"
          fi

  use-secret:
    needs: access-secret
    runs-on: ubuntu-latest
    steps:
      - name: Use USER_SECRET in another job
        env:
          USER_SECRET: ${{ needs.access-secret.outputs.user_secret }}
        run: |
          echo "Usando el secreto en otro job:"
          echo "El valor de USER_SECRET es: $USER_SECRET"
