name: Dynamic Secret Access

on:
  workflow_dispatch:
    inputs:
      user:
        description: "Nombre del usuario para buscar el secreto"
        required: true

jobs:
  access-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Set secret name based on input
        id: set-secret
        run: echo "SECRET_NAME=SECRET_${{ github.event.inputs.user }}" >> $GITHUB_ENV

      - name: Access the secret
        env:
          USER_SECRET: ${{ secrets[env.SECRET_NAME] || 'SECRET_NOT_FOUND' }}
        run: |
          if [ "$USER_SECRET" = "SECRET_NOT_FOUND" ]; then
            echo "El secreto para el usuario no existe o no fue encontrado."
            exit 1
          else
            echo "Secreto encontrado: $USER_SECRET"
          fi
