name: Dynamic Secret Access

on:
  workflow_dispatch:
    inputs:
      user:
        description: "Nombre del usuario para buscar el secreto"
        required: true

jobs:
  secrets-fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: dopplerhq/secrets-fetch-action@v1.2.0
      id: doppler
      with:
        doppler-token: ${{ secrets.DOPPLER_TOKEN }}
        inject-env-vars: true
    - run: printenv