name: "Validate Envs"
on:
  workflow_call:
    secrets:
        CUSTOM_LOCAL:
            required: true
        APP_TYPE:
            required: true
        DOMAIN:
            required: true
        ENV:
            required: true

jobs:
  env_validations:
    runs-on: ubuntu-latest
    steps:
    - name: Validate envs
      run: |
        if [ -z "${{ secrets.CUSTOM_LOCAL }}" ]; then
          echo "Error: CUSTOM_LOCAL is empty or not set."
          exit 1
        fi

        if [ -z "${{ secrets.APP_TYPE }}" ]; then
          echo "Error: APP_TYPE is empty or not set."
          exit 1
        fi

        if [ -z "${{ secrets.DOMAIN }}" ]; then
          echo "Error: DOMAIN is empty or not set."
          exit 1
        fi

        if [ -z "${{ secrets.ENV }}" ]; then
          echo "Error: ENV is empty or not set."
          exit 1
        fi

        echo "All required variables are set."
        
  host_validations:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install -r requirements.txt || echo "No dependencies required"

    - name: Run validation script
      run: python validate_targets.py

    
      